### ISSUE TITLE
LINE Engineering - 스프링부트 쿠버네티스 배포

### ISSUE THREAD

**Issue by ecsimsw** [ecsimsw/daily-note-public#4]
ref, `https://engineering.linecorp.com/ko/blog/apply-warm-up-in-spring-boot-and-kubernetes`
envs, `https://zingzai.medium.com/externalise-and-configure-spring-boot-environment-variables-on-kubernetes-ae28df48eae4`
deployment confiugration / hpa, `https://dev.to/airoasis/spring-boot-seobiseureul-wihan-kubernetes-seoljeong-3d72`

**Comment by ecsimsw** [comment]
https://github.com/ecsimsw/ecsimsw-kube/tree/main/src/mymarket

**Comment by ecsimsw** [comment]
My sample deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-server
  namespace: mymarket
  labels:
    app: products-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-server
  template:
    metadata:
      labels:
        app: products-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - products-server
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: products-server
          image: ghcr.io/ecsimsw/mymarket/products:latest
          envFrom:
          - configMapRef:
              name: products-config
          - secretRef:
              name: mymarket-mysql-secret
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 120
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 20
            periodSeconds: 120
          resources:
            requests:
              memory: 518Mi
            limits:
              memory: 518Mi
      imagePullSecrets:
        - name: ghcr-secret
  ```

**Comment by ecsimsw** [comment]
sample hpa

```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: products-server-hpa
  namespace: mymarket
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: products-server
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory                       # Percentage of requested memory
        target:
          type: Utilization
          averageUtilization: 80           # HPA controller scales the target such that the average utilization of the cpu in the application container of all the pods is 80%.
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0        # The number of seconds for which past recommendations should be considered while scaling up or down
      policies:
      - type: Pods
        value: 4
        periodSeconds: 15
      - type: Percent
        value: 100
        periodSeconds: 15                   # There are 2 policies where 4 pods or a 100% of the currently running replicas may at most be added every 15 seconds till the HPA reaches its steady state.
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 5
        periodSeconds: 60                   # To ensure that no more than 5 Pods are removed per minute, you can add a second scale-down policy with a fixed size of 5
      - type: Percent
        value: 100                          # The scaling target can be scaled down to the minimum allowed replicas.
        periodSeconds: 30
      selectPolicy: Min                     # Setting selectPolicy to Min means that the autoscaler chooses the policy that affects the smallest number of Pods:
```

**Comment by ecsimsw** [comment]
sample pdb
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: products-server-pdb
  namespace: mymarket
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: products-server
```
